### ISSUE TITLE
How to use this nice util?

### ISSUE THREAD

**Issue by egh-s** [jhonnold/node-tlcv#15]
I suppose it's a plug-in for TLCV?

I like to replace it with my crappy one - http://rebel13.nl/pgn4web-3.05/live-test.html

I agree with Ferdy the board size is a little bit too big.

**Comment by jhonnold** [comment]
Hey!

This is not a plugin, but a server that I've deployed and connects to Graham's TLCV broadcasts. If you'd like to use it yourself, I could work to make it so the setup is more configurable (at this time a lot of values are specific to Graham's broadcasts). 

If you'd like to switch to it quickly, I could also show you what exact values to change. Let me know if you have any other questions.

**Comment by jhonnold** [comment]
> I agree with Ferdy the board size is a little bit too big.

I agree. I'm quite busy with outside stuff at this time, but plan to address styling preferences in the form of customization when I have a bit of time.

**Comment by egh-s** [comment]
A setup would be great!

And I am not in a hurry :-)

**Comment by jhonnold** [comment]
@egh-s Please take a look to see if the configuration I allowed is enough for you to run your own.
