### ISSUE TITLE
PGNs of games as tourney plays out

### ISSUE THREAD

**Issue by ChrisWhittington** [jhonnold/node-tlcv#50]
Can we get at a page with PGNs of the tourney played so far? Would be useful. At the moment there doesn't seem to be an easy way to get at, say, the penultimate game PGN, let alone all the other priors.

**Comment by jhonnold** [comment]
Should hopefully be available moving forward @ tlcv.net/pgns

**Comment by ChrisWhittington** [comment]
Scid doesn't like the date format:

(game 1, line 1) Error parsing the tag pair: Date "Sun Jul 09 2023" ==> Date "????.??.??"

I guess it likes yyyy.mm.dd (Scid not speako Americano), maybe on basis of sorting

**Comment by jhonnold** [comment]
Working on improving filenames and directory structure, will update in this as well
