### ISSUE TITLE
FEN move count inconsistency

### ISSUE THREAD

**Issue by GediminasMasaitis** [jhonnold/node-tlcv#52]
When the opening line is running, FEN gets updated accordingly, but after the engines start playing, the move counter gets reset to 1.

For example:
![image](https://github.com/jhonnold/node-tlcv/assets/7861188/d9cec65f-12a9-4492-a10f-0a60310f4621)

This game is not 3 moves in.

**Comment by jhonnold** [comment]
Processing of certain was moves was failing when a duplicate receive caused a FEN reset. Resolved.
