### ISSUE TITLE
Variant boards have some sort of bug

### ISSUE THREAD

**Issue by tonymokonen** [jhonnold/node-tlcv#62]
Sometimes, when I am watching a game, the variant boards will have two black kings and one white king, or vice versa, or an obvious material imbalance in a position with an even score, because one of the pieces was not properly blanked out.  I am not sure if it is specific to Firefox, which is the browser I am using.

**Comment by jhonnold** [comment]
This seems to be an issue when receiving a frequent number of updates as the PV  is received en mass at low depths. Will look at a debounce option.

**Comment by jhonnold** [comment]
Hopefully fixed with #85
